version: '3'
services:  
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - SUPERSET_LOAD_EXAMPLES=no
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@superset.com
      - PYTHONPATH=/app/pythonpath
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_HOST=db
    volumes:
      - ./dados_processados:/app/data
    command: >
      bash -c "pip install pillow psycopg2-binary &&
              superset db upgrade &&
              superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
              superset init &&
              superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres:13
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
